server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123qweQ!
#  security:
#    user:
#      name: user
#      password: 111111

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

system:
  jwt:
    header: Authorization
    expire: 604800
    secret: aosjdojansdon123o123n23o4no23422